name: DocumentDB One-Time Snapshot

on:
  workflow_dispatch:
    inputs:
      aws-region:
        description: 'AWS region'
        required: true
      cluster-id:
        description: 'DocDB Cluster Identifier'
        required: true
      environment:
        description: 'Environment (e.g., dev, staging, regression, prod)'
        required: true
      release:
        description: 'Release Version'
        required: true

jobs:
  snapshot:
    runs-on: [self-hosted, aws-oidc]
    permissions:
      id-token: write
      contents: read    
    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::014562355322:role/GitHubOIDCRole
          aws-region: ${{ github.event.inputs.aws-region }}

      - name: Create DocumentDB snapshot
        id: create_snapshot
        run: |
          date=$(date +'%Y%m%d-%H%M%S')
          release_format=$(echo "${{ github.event.inputs.release }}" | sed 's/[^a-zA-Z0-9-]/-/g')
          snapshot_name="${{ github.event.inputs.environment }}-vip-before-${release_format}-upgrade-${date}"
          echo "snapshot_name=$snapshot_name" >> $GITHUB_ENV
          echo "Creating snapshot: $snapshot_name"
         

          aws docdb create-db-cluster-snapshot \
            --db-cluster-snapshot-identifier $snapshot_name \
            --db-cluster-identifier ${{ github.event.inputs.cluster-id }}

      - name: Verify snapshot status
        run: |
          echo "Checking status for: $snapshot_name"
          aws docdb describe-db-cluster-snapshots \
            --db-cluster-snapshot-identifier $snapshot_name \
            --query 'DBClusterSnapshots[0].[Status, PercentProgress]' \
            --output text

      - name: Wait until snapshot is available
        run: |
          echo "Waiting for snapshot: $snapshot_name"
          aws rds wait db-cluster-snapshot-available \
            --db-cluster-snapshot-identifier "$snapshot_name"
          echo "Snapshot is now available!"
