name: DocumentDB One-Time Snapshot

on:
  workflow_dispatch:
    inputs:
      aws-region:
        description: 'AWS region for DocumentDB'
        required: true
      cluster-id:
        description: 'DocumentDB cluster identifier'
        required: true
      aws-profile:
        description: 'AWS CLI profile name'
        required: true
      environment:
        description: 'Environment (e.g., regression, beta, staging or prod)'
        required: true
      release:
        description: 'Release version'
        required: true

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Create DocumentDB snapshot
        run: |
          DATE=$(date +'%Y%m%d-%H%M%S')
          SNAPSHOT_NAME="${{ github.event.inputs.environment }}-vip-before-${{ github.event.inputs.release }}-upgrade-${DATE}"
          echo "Creating snapshot: $SNAPSHOT_NAME"
          aws --profile ${{ github.event.inputs.aws-profile }} \
              --region ${{ github.event.inputs.aws-region }} \
              docdb create-db-cluster-snapshot \
              --db-cluster-snapshot-identifier $SNAPSHOT_NAME \
              --db-cluster-identifier ${{ github.event.inputs.cluster-id }}

